# Reducing the number of high fatality accidents

## 📖 Background
You work for the road safety team within the department of transport and are looking into how they can reduce the number of major incidents. The safety team classes major incidents as fatal accidents involving 3+ casualties. They are trying to learn more about the characteristics of these major incidents so they can brainstorm interventions that could lower the number of deaths. They have asked for your assistance with answering a number of questions.

## 💾 The data
The reporting department have been collecting data on every accident that is reported. They've included this along with a lookup file for 2020's accidents.

*Published by the department for transport. https://data.gov.uk/dataset/road-accidents-safety-data* 
*Contains public sector information licensed under the Open Government Licence v3.0.*

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns


accidents = pd.read_csv(r'./data/accident-data.csv')
accidents.head()

,accident_index,accident_year,accident_reference,longitude,latitude,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,...,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
0,2020010219808,2020,10219808,-0.254001,51.462262,3,1,1,04/02/2020,3,...,6,0,9,9,1,9,9,0,0,1
1,2020010220496,2020,10220496,-0.139253,51.470327,3,1,2,27/04/2020,2,...,6,0,0,4,1,1,1,0,0,1
2,2020010228005,2020,10228005,-0.178719,51.529614,3,1,1,01/01/2020,4,...,6,0,0,0,4,1,2,0,0,1
3,2020010228006,2020,10228006,-0.001683,51.541210,2,1,1,01/01/2020,4,...,6,0,0,4,4,1,1,0,0,1
4,2020010228011,2020,10228011,-0.137592,51.515704,3,1,2,01/01/2020,4,...,5,0,0,0,4,1,1,0,0,1

In [2]:
lookup = pd.read_csv(r'./data/road-safety-lookups.csv')
lookup.head()

,table,field name,code/format,label,note
0,Accident,accident_index,NaN,NaN,unique value for each accident. The accident_i...
1,Accident,accident_year,NaN,NaN,NaN
2,Accident,accident_reference,NaN,NaN,In year id used by the police to reference a c...
3,Accident,longitude,NaN,NaN,Null if not known
4,Accident,Latitude,NaN,NaN,Null if not known

## 💪 Competition challenge

Create a report that covers the following:

1. What time of day and day of the week do most major incidents happen?
2. Are there any patterns in the time of day/ day of the week when major incidents occur?
3. What characteristics stand out in major incidents compared with other accidents?
4. On what areas would you recommend the planning team focus their brainstorming efforts to reduce major incidents?

## 🧑‍⚖️ Judging criteria

| CATEGORY | WEIGHTING | DETAILS                                                              |
|:---------|:----------|:---------------------------------------------------------------------|
| **Recommendations** | 35%       | <ul><li>Clarity of recommendations - how clear and well presented the recommendation is.</li><li>Quality of recommendations - are appropriate analytical techniques used & are the conclusions valid?</li><li>Number of relevant insights found for the target audience.</li></ul>       |
| **Storytelling**  | 30%       | <ul><li>How well the data and insights are connected to the recommendation.</li><li>How the narrative and whole report connects together.</li><li>Balancing making the report in depth enough but also concise.</li></ul> |
| **Visualizations** | 25% | <ul><li>Appropriateness of visualization used.</li><li>Clarity of insight from visualization.</li></ul> |
| **Votes** | 10% | <ul><li>Up voting - most upvoted entries get the most points.</li></ul> |

## ✅ Checklist before publishing into the competition
- Rename your workspace to make it descriptive of your work. N.B. you should leave the notebook name as notebook.ipynb.
- Remove redundant cells like the judging criteria so the workbook is focused on your story.
- Make sure the workbook reads well and explains how you found your insights.
- Check that all the cells run without error.

## ⌛️ Time is ticking. Good luck!

In [3]:
accidents

,accident_index,accident_year,accident_reference,longitude,latitude,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,...,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
0,2020010219808,2020,10219808,-0.254001,51.462262,3,1,1,04/02/2020,3,...,6,0,9,9,1,9,9,0,0,1
1,2020010220496,2020,10220496,-0.139253,51.470327,3,1,2,27/04/2020,2,...,6,0,0,4,1,1,1,0,0,1
2,2020010228005,2020,10228005,-0.178719,51.529614,3,1,1,01/01/2020,4,...,6,0,0,0,4,1,2,0,0,1
3,2020010228006,2020,10228006,-0.001683,51.541210,2,1,1,01/01/2020,4,...,6,0,0,4,4,1,1,0,0,1
4,2020010228011,2020,10228011,-0.137592,51.515704,3,1,2,01/01/2020,4,...,5,0,0,0,4,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91194,2020991027064,2020,991027064,-2.926320,56.473539,2,2,1,12/08/2020,4,...,4,959,0,0,1,1,1,0,0,1
91195,2020991029573,2020,991029573,-4.267565,55.802353,3,1,1,13/11/2020,6,...,6,0,0,0,1,1,1,0,0,1
91196,2020991030297,2020,991030297,-2.271903,57.186317,2,2,1,15/04/2020,4,...,6,0,0,0,1,1,1,0,0,2
91197,2020991030900,2020,991030900,-3.968753,55.950940,3,2,1,15/12/2020,3,...,6,0,0,0,1,1,1,0,0,1
91198,2020991032575,2020,991032575,-4.561040,56.003843,3,1,1,25/08/2020,3,...,6,0,0,0,1,1,1,0,2,1

In [4]:
accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91199 entries, 0 to 91198
Data columns (total 27 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   accident_index                           91199 non-null  object
 1   accident_year                            91199 non-null  int64
 2   accident_reference                       91199 non-null  object
 3   longitude                                91185 non-null  float64
 4   latitude                                 91185 non-null  float64
 5   accident_severity                        91199 non-null  int64
 6   number_of_vehicles                       91199 non-null  int64
 7   number_of_casualties                     91199 non-null  int64
 8   date                                     91199 non-null  object
 9   day_of_week                              91199 non-null  int64
 10  time                                     91199 non-null  object
 11  first_road_class                         91199 non-null  int64
 12  first_road_number                        91199 non-null  int64
 13  road_type                                91199 non-null  int64
 14  speed_limit                              91199 non-null  int64
 15  junction_detail                          91199 non-null  int64
 16  junction_control                         91199 non-null  int64
 17  second_road_class                        91199 non-null  int64
 18  second_road_number                       91199 non-null  int64
 19  pedestrian_crossing_human_control        91199 non-null  int64
 20  pedestrian_crossing_physical_facilities  91199 non-null  int64
 21  light_conditions                         91199 non-null  int64
 22  weather_conditions                       91199 non-null  int64
 23  road_surface_conditions                  91199 non-null  int64
 24  special_conditions_at_site               91199 non-null  int64
 25  carriageway_hazards                      91199 non-null  int64
 26  urban_or_rural_area                      91199 non-null  int64
dtypes: float64(2), int64(21), object(4)
memory usage: 18.8+ MB

In [5]:
lookup

,table,field name,code/format,label,note
0,Accident,accident_index,NaN,NaN,unique value for each accident. The accident_i...
1,Accident,accident_year,NaN,NaN,NaN
2,Accident,accident_reference,NaN,NaN,In year id used by the police to reference a c...
3,Accident,longitude,NaN,NaN,Null if not known
4,Accident,Latitude,NaN,NaN,Null if not known
...,...,...,...,...,...
124,Accident,carriageway_hazards,9,unknown (self reported),NaN
125,Accident,urban_or_rural_area,1,Urban,field introduced in 1994
126,Accident,urban_or_rural_area,2,Rural,field introduced in 1994
127,Accident,urban_or_rural_area,3,Unallocated,field introduced in 1994
128,Accident,urban_or_rural_area,-1,Data missing or out of range,field introduced in 1994

In [6]:
lookup[lookup['field name'] == 'accident_severity']

      table         field name code/format    label note
5  Accident  accident_severity           1    Fatal  NaN
6  Accident  accident_severity           2  Serious  NaN
7  Accident  accident_severity           3   Slight  NaN

In [7]:
accidents['accident_severity'].unique()

array([3, 2, 1], dtype=int64)

In [8]:
lookup[['field name', 'code/format', 'label']]

              field name code/format                         label
0         accident_index         NaN                           NaN
1          accident_year         NaN                           NaN
2     accident_reference         NaN                           NaN
3              longitude         NaN                           NaN
4               Latitude         NaN                           NaN
..                   ...         ...                           ...
124  carriageway_hazards           9       unknown (self reported)
125  urban_or_rural_area           1                         Urban
126  urban_or_rural_area           2                         Rural
127  urban_or_rural_area           3                   Unallocated
128  urban_or_rural_area          -1  Data missing or out of range

[129 rows x 3 columns]

In [9]:
for field, code, label in lookup[['field name', 'code/format', 'label']].values:
    print(field, code, label)
    break

accident_index nan nan

def to_replace(df):
    lookup_values = lookup[['field name', 'code/format', 'label']].values

    try:
        for field, code, label in lookup_values:
            if code is not np.nan:
                df[field].replace(int(code), label, inplace = True) # e.g on def['accident seveerity'], replade code 3 with the label severe
    except:
        print(code)

the above code will only change the first column that is not null and that's because the for loop is inside the try block. This means that it would truncate as soon as it gets the fiirst error.

In [23]:
def to_replace(df):
    lookup_values = lookup[['field name', 'code/format', 'label']].values
    for field, code, label in lookup_values:
        try:
            if code is not np.nan:
                    df[field].replace(int(code), label, inplace = True) # e.g on def['accident seveerity'], replade code 3 with the label severe
        except:
            print(code)

In [24]:
to_replace(accidents)

(DD/MM/YYYY)
(HH:MM)
1 to 9999

C:\Users\admin\AppData\Local\Temp\ipykernel_34720\3341232349.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[field].replace(int(code), label, inplace = True) # e.g on def['accident seveerity'], replade code 3 with the label severe

1 to 9999

In [25]:
accidents

,accident_index,accident_year,accident_reference,longitude,latitude,accident_severity,number_of_vehicles,number_of_casualties,date,day_of_week,...,second_road_class,second_road_number,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
0,2020010219808,2020,10219808,-0.254001,51.462262,Slight,1,1,04/02/2020,Tuesday,...,Unclassified,first_road_class is C or Unclassified. These r...,unknown (self reported),unknown (self reported),Daylight,Unknown,unknown (self reported),NaN,NaN,Urban
1,2020010220496,2020,10220496,-0.139253,51.470327,Slight,1,2,27/04/2020,Monday,...,Unclassified,first_road_class is C or Unclassified. These r...,None within 50 metres,"Pelican, puffin, toucan or similar non-junctio...",Daylight,Fine no high winds,Dry,NaN,NaN,Urban
2,2020010228005,2020,10228005,-0.178719,51.529614,Slight,1,1,01/01/2020,Wednesday,...,Unclassified,first_road_class is C or Unclassified. These r...,None within 50 metres,No physical crossing facilities within 50 metres,Darkness - lights lit,Fine no high winds,Wet or damp,NaN,NaN,Urban
3,2020010228006,2020,10228006,-0.001683,51.541210,Serious,1,1,01/01/2020,Wednesday,...,Unclassified,first_road_class is C or Unclassified. These r...,None within 50 metres,"Pelican, puffin, toucan or similar non-junctio...",Darkness - lights lit,Fine no high winds,Dry,NaN,NaN,Urban
4,2020010228011,2020,10228011,-0.137592,51.515704,Slight,1,2,01/01/2020,Wednesday,...,C,first_road_class is C or Unclassified. These r...,None within 50 metres,No physical crossing facilities within 50 metres,Darkness - lights lit,Fine no high winds,Dry,NaN,NaN,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91194,2020991027064,2020,991027064,-2.926320,56.473539,Serious,2,1,12/08/2020,Wednesday,...,B,959,None within 50 metres,No physical crossing facilities within 50 metres,Daylight,Fine no high winds,Dry,NaN,NaN,Urban
91195,2020991029573,2020,991029573,-4.267565,55.802353,Slight,1,1,13/11/2020,Friday,...,Unclassified,first_road_class is C or Unclassified. These r...,None within 50 metres,No physical crossing facilities within 50 metres,Daylight,Fine no high winds,Dry,NaN,NaN,Urban
91196,2020991030297,2020,991030297,-2.271903,57.186317,Serious,2,1,15/04/2020,Wednesday,...,Unclassified,first_road_class is C or Unclassified. These r...,None within 50 metres,No physical crossing facilities within 50 metres,Daylight,Fine no high winds,Dry,NaN,NaN,Rural
91197,2020991030900,2020,991030900,-3.968753,55.950940,Slight,2,1,15/12/2020,Tuesday,...,Unclassified,first_road_class is C or Unclassified. These r...,None within 50 metres,No physical crossing facilities within 50 metres,Daylight,Fine no high winds,Dry,NaN,NaN,Urban
91198,2020991032575,2020,991032575,-4.561040,56.003843,Slight,1,1,25/08/2020,Tuesday,...,Unclassified,first_road_class is C or Unclassified. These r...,None within 50 metres,No physical crossing facilities within 50 metres,Daylight,Fine no high winds,Dry,NaN,Other object on road,Urban

In [27]:
lookup[0:20]

,table,field name,code/format,label,note
0,Accident,accident_index,NaN,NaN,unique value for each accident. The accident_i...
1,Accident,accident_year,NaN,NaN,NaN
2,Accident,accident_reference,NaN,NaN,In year id used by the police to reference a c...
3,Accident,longitude,NaN,NaN,Null if not known
4,Accident,Latitude,NaN,NaN,Null if not known
5,Accident,accident_severity,1,Fatal,NaN
6,Accident,accident_severity,2,Serious,NaN
7,Accident,accident_severity,3,Slight,NaN
8,Accident,number_of_vehicles,NaN,NaN,NaN
9,Accident,number_of_casualties,NaN,NaN,NaN
10,Accident,date,(DD/MM/YYYY),NaN,NaN
11,Accident,day_of_week,1,Sunday,NaN
12,Accident,day_of_week,2,Monday,NaN
13,Accident,day_of_week,3,Tuesday,NaN
14,Accident,day_of_week,4,Wednesday,NaN
15,Accident,day_of_week,5,Thursday,NaN
16,Accident,day_of_week,6,Friday,NaN
17,Accident,day_of_week,7,Saturday,NaN
18,Accident,time,(HH:MM),NaN,Null if not known
19,Accident,first_road_class,1,Motorway,NaN

In [34]:
def check_note(field):
    return lookup[field == lookup['field name']]

In [35]:
check_note('first_road_class')

       table        field name code/format         label note
19  Accident  first_road_class           1      Motorway  NaN
20  Accident  first_road_class           2          A(M)  NaN
21  Accident  first_road_class           3             A  NaN
22  Accident  first_road_class           4             B  NaN
23  Accident  first_road_class           5             C  NaN
24  Accident  first_road_class           6  Unclassified  NaN

In [36]:
check_note('road_type')

       table field name code/format                         label note
28  Accident  road_type           1                    Roundabout  NaN
29  Accident  road_type           2                One way street  NaN
30  Accident  road_type           3              Dual carriageway  NaN
31  Accident  road_type           6            Single carriageway  NaN
32  Accident  road_type           7                     Slip road  NaN
33  Accident  road_type           9                       Unknown  NaN
34  Accident  road_type          12      One way street/Slip road  NaN
35  Accident  road_type          -1  Data missing or out of range  NaN

In [38]:
accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91199 entries, 0 to 91198
Data columns (total 27 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   accident_index                           91199 non-null  object
 1   accident_year                            91199 non-null  int64
 2   accident_reference                       91199 non-null  object
 3   longitude                                91185 non-null  float64
 4   latitude                                 91185 non-null  float64
 5   accident_severity                        91199 non-null  object
 6   number_of_vehicles                       91199 non-null  int64
 7   number_of_casualties                     91199 non-null  int64
 8   date                                     91199 non-null  object
 9   day_of_week                              91199 non-null  object
 10  time                                     91199 non-null  object
 11  first_road_class                         91199 non-null  object
 12  first_road_number                        91199 non-null  object
 13  road_type                                91199 non-null  object
 14  speed_limit                              91199 non-null  object
 15  junction_detail                          91199 non-null  object
 16  junction_control                         91199 non-null  object
 17  second_road_class                        91199 non-null  object
 18  second_road_number                       91199 non-null  object
 19  pedestrian_crossing_human_control        91199 non-null  object
 20  pedestrian_crossing_physical_facilities  91199 non-null  object
 21  light_conditions                         91199 non-null  object
 22  weather_conditions                       91199 non-null  object
 23  road_surface_conditions                  91199 non-null  object
 24  special_conditions_at_site               3890 non-null   object
 25  carriageway_hazards                      3318 non-null   object
 26  urban_or_rural_area                      91199 non-null  object
dtypes: float64(2), int64(3), object(22)
memory usage: 18.8+ MB

In [43]:
#accidents['date'] = pd.to_datetime(accidents.date)
accidents['date'] = pd.to_datetime(accidents['date'], dayfirst=True)

In [46]:
accidents['time'] = pd.to_datetime(accidents.time, format = '%H:%M')
accidents['time']

0       1900-01-01 09:00:00
1       1900-01-01 13:55:00
2       1900-01-01 01:25:00
3       1900-01-01 01:50:00
4       1900-01-01 02:25:00
                ...
91194   1900-01-01 14:30:00
91195   1900-01-01 15:05:00
91196   1900-01-01 12:42:00
91197   1900-01-01 14:00:00
91198   1900-01-01 13:50:00
Name: time, Length: 91199, dtype: datetime64[ns]